const fortunes = [
"Rekabete kapılmaktan korkma.",
"Önünde heyecan verici bir fırsat var.",
"Huzuru seversin.",
"Zihnini hazırla… özgüven seni ileriye taşıyacak.",
"Her zaman gerçek dostlarla çevrili olacaksın.",
"Fikirlerini sat — olağanüstü bir değere sahipler.",
"Üstlendiğin her işi başlatıp tamamlayabilecek güce sahipsin.",
"Sen nazik ve arkadaş canlısısın.",
"Yaşının ötesinde bir bilgelik taşıyorsun.",
"Birden çok işi aynı anda yürütebilme yeteneğin seni çok ileri götürecek.",
"Rutin bir görev büyüleyici bir maceraya dönüşecek.",
"Yeni kıyafetler gerektiren tüm girişimlere dikkat et.",
"İşine, sözüne ve dostuna sadık ol.",
"İyilik, asla kaybettirmeyen tek yatırımdır.",
"Bin millik bir yolculuk tek bir adımla başlar.",
"İncitilmeleri unut; iyilikleri asla unutma.",
"Kendine saygı duy, başkaları da sana saygı duysun.",
"Bir insan kendi onayı olmadan rahat edemez.",
"Her zaman doğru olanı yap. Bu bazılarını memnun edecek, geri kalanını ise şaşırtacaktır.",
"Dışarıda kalmak, çıkmaktan daha kolaydır.",
"Her gün şarkı söyle ve hüzünlü mavileri kov.",
"Beklenmedik bir kaynaktan para alacaksın.",
"Tutum küçük bir şeydir ama büyük fark yaratır.",
"Önündeki birçok keyif için plan yap.",
"Tecrübe en iyi öğretmendir.",
"Eşinle mutlu olacaksın.",
"Beklenmeyeni bekle.",
"Sağlıklı kal. Bir mil yürü.",
"Birlikte oynayan aile, birlikte kalır.",
"Hayatın daha tatlı olması için çikolata ye.",
"Bir karar verdiğinde evren onu gerçekleştirmek için iş birliği yapar.",
"Kendini birine gerekli kıl.",
"Bir dosta sahip olmanın tek yolu, dost olmaktır.",
"Coşku olmadan hiçbir büyük şey başarılmamıştır.",
"Kimse izlemiyormuş gibi dans et.",
"Bu günü son gününmüş gibi yaşa.",
"Hayatın mutlu ve huzurlu olacak.",
"Sevince uzan, gerisi kendiliğinden gelecektir.",
"Hayallerinin yönünde ilerle.",
"Dikildiğin yerde çiçek aç.",
"Takdir et. Takdir et. Takdir et.",
"Mutlu haberler yolda.",
"Eğlenceli.",
"Kapalı bir ağız ayak toplamaz.",
"Toprak atan, zemin kaybediyor.",
"Karamsardan borç al. Geri ödenmesini beklemezler.",
"Hayat, sen başka planlar yaparken başına gelenlerdir.",
"Yardım edin! Bir fal kurabiyesi fabrikasında tutsak tutuluyorum.",
"Romantik.",
"Cennet, sevginin olduğu yerdir.",
"Sevdiğin kişi düşündüğünden daha yakında.",
"Sevgi yabani çiçekler gibidir… çoğu zaman en beklenmedik yerlerde bulunur.",
"Rüyalarda ve aşkta imkânsız diye bir şey yoktur.",
"Sevgi bulunacak bir şey değildir. Sevgi seni bulan bir şeydir.",
"Gerçek aşk her gün gelmez; kalbini takip et, doğru cevabı o bilir.",
"Cesaret ettiğin anda yol açılır.",
"Sabır, beklediğinden daha büyük ödüller getirir.",
"Küçük bir adım büyük bir değişimi başlatır.",
"Kalbinin sesini dinle, seni yanıltmaz.",
"Bugün attığın tohum yarın yeşerecek.",
"Şans, hazırlıklı olanı sever.",
"Gülümsemen kapıları açacak.",
"Doğru zamanda doğru yerde olacaksın.",
"İç huzurun en büyük gücün.",
"Emeklerin karşılıksız kalmayacak.",
"Yeni bir tanışma hayatını renklendirecek.",
"Kendine güvendiğinde her şey kolaylaşır.",
"İyilik yaptıkça yolun aydınlanır.",
"Beklediğin haber düşündüğünden erken gelecek.",
"Değişim sana iyi gelecek.",
"Hayat seni destekliyor.",
"Zor sandığın şey sandığından kısa sürecek.",
"Bugün aldığın karar geleceğini şekillendirir.",
"Ne verirsen onu alırsın.",
"Kalbin ferahlayacak.",
"Umudunu koru, mucizeler sessiz gelir.",
"Bir tebessüm gününü değiştirecek.",
"Doğru seçim içinden gelen seçimdir.",
"Yeni bir yolculuk ufkunu genişletecek.",
"İçindeki çocuk sana rehberlik edecek.",
"Beklenmedik bir destek alacaksın.",
"Şükür, bolluğun anahtarıdır.",
"Adımların seni doğru yere götürüyor.",
"Hayatla barıştıkça güzelleşirsin.",
"Bugün kendin için bir şey yap.",
"Kalıcı mutluluk küçük anlarda gizlidir.",
"Doğru insanlar seni bulacak.",
"İnandığın şey gerçekleşmeye yakın.",
"Ruhun dinlenmeye ihtiyaç duyuyor.",
"Sevgi paylaştıkça çoğalır.",
"Cesur bir karar seni özgürleştirecek.",
"İç sesin seni uyarıyor, dinle.",
"Şanslı bir tesadüf kapıda.",
"Bugün verdiğin emek yarın gülümsetecek.",
"Kendini olduğun gibi kabul et.",
"Her son yeni bir başlangıçtır.",
"Yolun açık, kalbin rahat olsun.",
"Mutluluk sen fark etmeden yaklaşıyor.",
"Küçük değişiklikler büyük etki yaratır.",
"Hayat sana nazik davranıyor.",
"Doğru zamanda konuşacaksın.",
"Bir dileğin gerçekleşme yolunda.",
"Kalbini yoran yükler hafifliyor.",
"Yeni bir fikir sana kazanç getirecek.",
"Sevdiğin şeyler seni bulur.",
"İç huzurun yüzüne yansıyacak.",
"Bugün şans senden yana.",
"Doğru karar sessiz gelir.",
"Bir kapı kapanır, diğeri açılır.",
"İçten bir teşekkür mucize yaratır.",
"Yaptığın iyilik sana dönecek.",
"Hayatın ritmine güven.",
"Beklemediğin bir an seni mutlu edecek.",
"Doğru yoldasın, devam et.",
"Kalbin hafifliyor.",
"Yeni bir başlangıç için hazırsın.",
"Mutluluk paylaştıkça büyür.",
"İçindeki gücü küçümseme.",
"Bugün kendinle gurur duyacaksın.",
"Sabır, anahtarını buluyor.",
"Hayat sana gülümsüyor.",
"Bir dosttan güzel bir haber alacaksın.",
"İnancın seni ileri taşıyacak.",
"Zaman her şeyi yerine oturtur.",
"İç huzurun artıyor.",
"Bugün küçük bir sürpriz var.",
"Kendine dürüst ol.",
"Şans, niyetini fark etti.",
"Kalbin doğruyu biliyor.",
"Yeni bir fırsat seni bekliyor.",
"Yolun sevgiyle kesişecek.",
"Bugün verdiğin karar doğru.",
"Mutluluk sana yakışıyor.",
"Hayatın rengi değişiyor.",
"İçten gelen başarı kalıcıdır.",
"Bir gülüş her şeyi değiştirebilir.",
"Bugün umut kazanacak.",
"Kalbin hafif, yolun açık.",
"İstediğin cevap yakında.",
"Hayatla uyum içindesin.",
"Şanslı bir dönem başlıyor.",
"İçindeki ışık yolunu aydınlatıyor."
];

const shownFortunes = new Set();

function showFortune() {
  // Tüm mesajlar gösterildiyse tekrar gösterme veya resetleme yapılabilir
  if (shownFortunes.size === fortunes.length) {
    document.getElementById("fortune-text").innerText = "Tüm mesajlar gösterildi. Sayfayı yenileyin.";
    return;
  }

  let randomIndex;
  do {
    randomIndex = Math.floor(Math.random() * fortunes.length);
  } while (shownFortunes.has(randomIndex));

  shownFortunes.add(randomIndex);
  document.getElementById("fortune-text").innerText = fortunes[randomIndex];
}